name: ci-sonarcloud
on:
  pull_request:
    branches:
      - main

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm i
      - name: Configure CI
        run: npm ci
      - name: Play tests
        run: npm test